resume/resume/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user.urls", namespace="user")),
]

resume/user/urls.py
from django.urls import path, include
from user import views

app_name = "user"

urlpatterns = [     
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
]

resume/user/models.py
from django.db import models

# Create your models here.

resume/user/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [ "username", "email","password"]
        widgets = {
            "password" : forms.widgets.PasswordInput(attrs = {"class" : "hello", "placeholder" : "Enter strong password"})
        }

resume/user/views.py
from django.shortcuts import render, reverse
from user.forms import UserForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http.response import HttpResponseRedirect

from user.functions import generate_form_errors


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)

            user = User.objects.create_user(
                username = instance.username,
                password = instance.password,
                email = instance.email,
            )

            user = authenticate(request, username=instance.username, password = instance.password)
            auth_login(request, user)

            return HttpResponseRedirect(reverse("user:index"))
        else:
            message = generate_form_errors(form)
            form = UserForm()
            context = {
                "title" : "Signup",
                "error" : True,
                "message" : message,
                "form" : form
            }
            return render(request, "signup.html", context = context)
    else:
        form = UserForm()
        context ={
            "title": "Signup",
            "form": form,
        }
        return render(request, "signup.html", context=context)
    

def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect("/")
            else:
                context = {
                    "error" : True,
                    "message" : "Invalid username or password",
                }
                return render(request, "login.html", context=context)
        else:
                context = {
                    "error" : True,
                    "message" : "Invalid username or password",
                }
                return render(request, "login.html", context=context)
    else:
        context = {
            "message" : "Invalid username or password",
        }
        return render(request, "login.html", context=context)

def index(request):
    return render(request, "ind.html")

resume/templates/ind.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body></body>
    <h1>Index</h1>
    <div class="btn">
        <a href="signup/"><button>Signup</button></a>
        <a href="login/"><button>Login</button></a>
    </div>
</html>

resume/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <h1>Login</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div>
                <label for="">Username</label>
                <input type="text" name="username" id="" />
            </div>
            <div>
                <label for="">Password</label>
                <input type="password" name="password" id="" />
            </div>
            {% if error %}
            <p>{{message}}</p>
            {% endif %}
            <button type="submit">Log in</button>
            <a href="{% url 'user:signup' %}">Already have an Account??</a>
        </form>
    </body>
</html>

resume/templates/signup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <h1>Signup</h1>
        <form action="" method="post">
            {% csrf_token %} {% for field in form %}
            <div class="input_container">
                <label for="{{field.id_for_label}}">{{field.label}}</label>
                {{field}}
            </div>
            {% endfor %}
            <div class="submit_container">
                {% if error %}
                <p class="error-message">{{message}}</p>
                {% endif %}
                <button type="submit">Create Account</button>
                <a href="{% url 'user:login' %}">Login</a>
            </div>
        </form>
    </body>
</html>